name: Update Forecast Data

on:
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-forecast:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml
        
    - name: Generate forecast data
      run: |
        python3 generate_static_data.py
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add data/*.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update forecast data - $(date -u)" && git push)
